import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const locales = ["en", "mnw", "my"];

function quoted(line, file, lineNumber) {
  const start = line.indexOf('"');
  if (start < 0) throw new Error(`${file}:${lineNumber}: expected a quoted PO string`);
  try {
    return JSON.parse(line.slice(start));
  } catch {
    throw new Error(`${file}:${lineNumber}: invalid PO string`);
  }
}

function parsePo(source, file) {
  const messages = {};
  let entry = null;
  let field = null;
  function finish() {
    if (!entry) return;
    if (entry.msgid) messages[entry.msgid] = entry.msgstr;
    entry = null;
    field = null;
  }
  source.split(/\r?\n/u).forEach((line, index) => {
    const lineNumber = index + 1;
    if (!line.trim()) { finish(); return; }
    if (line.startsWith("#")) return;
    if (line.startsWith("msgid ")) {
      finish();
      entry = { msgid: quoted(line, file, lineNumber), msgstr: "" };
      field = "msgid";
      return;
    }
    if (line.startsWith("msgstr ")) {
      if (!entry) throw new Error(`${file}:${lineNumber}: msgstr without msgid`);
      entry.msgstr = quoted(line, file, lineNumber);
      field = "msgstr";
      return;
    }
    if (line.startsWith('"')) {
      if (!entry || !field) throw new Error(`${file}:${lineNumber}: orphaned PO continuation`);
      entry[field] += quoted(line, file, lineNumber);
      return;
    }
    throw new Error(`${file}:${lineNumber}: unsupported PO syntax`);
  });
  finish();
  return messages;
}

const catalogs = {};
for (const locale of locales) {
  const file = resolve(root, "locales", `${locale}.po`);
  catalogs[locale] = parsePo(await readFile(file, "utf8"), file);
}

const englishIds = new Set(Object.keys(catalogs.en));
for (const locale of locales.slice(1)) {
  for (const id of Object.keys(catalogs[locale])) {
    if (!englishIds.has(id)) throw new Error(`${locale}.po contains an unknown msgid: ${id}`);
  }
}

if (process.argv.includes("--sync")) {
  for (const locale of locales.slice(1)) {
    const header = [
      'msgid ""',
      'msgstr ""',
      '"Project-Id-Version: YAMU 2.0\\n"',
      `"Language: ${locale}\\n"`,
      '"Content-Type: text/plain; charset=UTF-8\\n"',
      "",
    ];
    const entries = Object.keys(catalogs.en).flatMap((msgid) => [
      `msgid ${JSON.stringify(msgid)}`,
      `msgstr ${JSON.stringify(catalogs[locale][msgid] || "")}`,
      "",
    ]);
    await writeFile(resolve(root, "locales", `${locale}.po`), `${[...header, ...entries].join("\n")}\n`);
  }
  console.log("Synchronized untranslated entries into mnw.po and my.po.");
}

const output = `/* This file is generated by scripts/compile-locales.mjs. */\nexport const PO_CATALOGS = ${JSON.stringify(catalogs, null, 2)} as const;\n`;
await writeFile(resolve(root, "lib", "locales.generated.ts"), output);
console.log(`Compiled ${englishIds.size} messages across ${locales.length} locales.`);
